import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import MainNav from "@/components/layout/MainNav";
import { HeroHighlight } from "@/components/ui/bgDot";
import { IBM_Plex_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "./context/userContext";
import { headers } from "next/headers"; // Import headers to access the request
import AdminNav from "@/components/layout/AdminNav";
import Sidebar from "@/components/layout/navSidbar";
import AdminSidebar from "@/components/layout/navSidbarAdmin";

const IBM_Font = IBM_Plex_Mono({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersResult = await headers();

  // Get the custom "x-layout" header
  const layoutType = headersResult.get("x-layout");

  // Check if the path is for the admin route
  const isAdmin = layoutType === "admin";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${IBM_Font.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <UserProvider>
            <HeroHighlight>
              <div className="min-h-screen grid md:grid-cols-4  text-slate-50">
                {isAdmin ? <AdminSidebar /> : <Sidebar />}
                <main className="md:col-span-4 lg:col-span-3  w-full">
                  {children}
                  <Footer />
                </main>
              </div>
            </HeroHighlight>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
