import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import MainNav from "@/components/layout/MainNav";
import { HeroHighlight } from "@/components/ui/bgDot";
import { IBM_Plex_Mono } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "./context/userContext";
import { headers } from "next/headers";
import Sidebar from "@/components/sidebar/navSidbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { useSidebar } from "@/components/ui/sidebar";
import ContentLayout from "@/components/sidebar/contentLayout";

const IBM_Font = IBM_Plex_Mono({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersResult = await headers();
  const layoutType = headersResult.get("x-layout");
  const isAdmin = layoutType === "admin";

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${IBM_Font.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <UserProvider>
            <HeroHighlight>
              <SidebarProvider>
                <ContentLayout isAdmin={isAdmin}>{children}</ContentLayout>
              </SidebarProvider>
            </HeroHighlight>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
