import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import MainNav from "@/components/layout/MainNav";
import { HeroHighlight } from "@/components/ui/bgDot";
import { IBM_Plex_Mono } from "next/font/google";
import {ThemeProvider} from "next-themes"

const IBM_Font = IBM_Plex_Mono({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${IBM_Font.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <HeroHighlight>
            <div className="min-h-screen flex flex-col text-slate-50">
              <MainNav />
              <main>{children}</main>
              <Footer />
            </div>
          </HeroHighlight>
        </ThemeProvider>
      </body>
    </html>
  );
}
